import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'; 
import "./globals.css";
import { Toaster, toast } from 'sonner'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body
        className={`antialiased` } 
      >
        {children}
        <Toaster position="top-center" richColors closeButton />
      </body>
    </html>
  );
}
